- name: Install Stable repos
  community.kubernetes.helm_repository:
    name: stable
    repo_url: "https://charts.helm.sh/stable"

- name: Update helm repos
  command: helm repo update
  delegate_to: localhost

- name: Create namespace
  community.kubernetes.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: namespace
    state: present

- name: Add Voight.org Certificates
  kubernetes.core.helm:
    name: "{{ deployment }}-certificates"
    chart_ref: ./roles/common/files/global
    release_namespace: "{{ namespace }}"
    release_values:
      namespace: "{{ namespace }}"
      tls:
        key: "{{ voightorgkey }}"
        crt: "{{ voightorgcrt }}"
        ca: "{{ voightorgca }}"
      openldapconfig:
        password: "{{ openldapconfigpassword }}"
      openldapadmin:
        password: "{{ openldapadminpassword }}"

- name: Apply OpenLDAP
  kubernetes.core.helm:
    name: "{{ deployment }}"
    chart_ref: stable/openldap
    release_namespace: "{{ namespace }}"
    release_values:
      image:
        tag: 1.5.0
      tls:
        enabled: true
        secret: "site-cert"
      CA:
        enabled: true
        secret: "site-ca"
      service:
        loadBalancerIP: 192.168.137.82
        type: LoadBalancer
      env:
        LDAP_ORGANISATION: "Voight Household"
        LDAP_DOMAIN: "voight.org"
        LDAP_BACKEND: "true"
      persistence:
        enabled: true
        existingClaim: "openldap-pvc"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
