apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldap-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: ldap-pvc
    namespace: authentication
  nfs:
    server: 192.168.137.3
    path: "/volume1/OpenLDAP"
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-pvc
  namespace: authentication
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: "ldap-pv"