# You would run this on the Kubernetes Control Plane
# Important: Run this first!

- name: Install OpenLDAP
  hosts: controlplane
  vars_files:
    - files/openldap-vault.yaml
  vars:
    namespace: authentication

  tasks:
    - name: Install Stable repos
      community.kubernetes.helm_repository:
        name: stable
        repo_url: "https://charts.helm.sh/stable"
      delegate_to: localhost

    - name: Update helm repos
      command: helm repo update
      delegate_to: localhost

    - name: Create namespace
      community.kubernetes.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: namespace
        state: present
      delegate_to: localhost

    - name: Copy global chart
      copy:
        src: files/global
        dest: /tmp/
      delegate_to: localhost

    - name: Copy ca cert
      copy:
        src: files/ca.crt
        dest: /tmp/
      delegate_to: localhost

    - name: Copy voight.org cert
      copy:
        src: files/voight.org.crt
        dest: /tmp/
      delegate_to: localhost

    - name: Add Voight.org Certificates
      command: >
        helm upgrade -i -n "{{ namespace }}" ldapcertificates /tmp/global
        --set-file tls.crt=/tmp/voight.org.crt
        --set tls.key='{{ voightorgkey }}'
        --set-file ca.crt=/tmp/ca.crt
        --set openldapconfig.namespace='{{ namespace }}'
      delegate_to: localhost

    - name: Apply OpenLDAP Secrets
      command: >
        helm upgrade -i -n {{ namespace }} openldapsecrets ../openldap
        --set openldapconfig.password='{{ openldapconfigpassword }}'
        --set openldapadmin.password='{{ openldapadminpassword }}'
        --set openldapconfig.namespace='{{ namespace }}'
      delegate_to: localhost

    - name: Apply OpenLDAP chart
      command: helm upgrade -i -n {{ namespace }} openldap stable/openldap -f ../openldap-values.yaml
      delegate_to: localhost

    - name: Add LDAP Users
      command: echo "Run your slapd script offline for now."