# You would run this on the Kubernetes Raspberry Pi Control Plane
# Important: Run this first!

- name: Reset OpenLDAP
  hosts: controlplane
  vars:
    namespace: authentication

  tasks:
    - name: Helm Uninstall OpenLDAP
      command: helm uninstall -n {{ namespace }} openldap

    - name: Uninstall LDAP Secrets
      command: helm uninstall -n {{ namespace }} openldapsecrets

    - name: Uninstall LDAP Certificates
      command: helm uninstall -n {{ namespace }} ldapcertificates

